name: CI Proyecto Automatizacion   # Nombre del workflow que aparecer√° en GitHub Actions

# Eventos que disparan este workflow:
on:
  push:
    branches: [main,develop]       # Ejecutar CI en cada push a las ramas main y develop
  pull_request:
    branches: [main,develop]       # Ejecutar CI en cada PR hacia main o develop

jobs:
  test:
    runs-on: ubuntu-latest         # El job correr√° en un runner Linux Ubuntu m√°s reciente

    env:
      PYTHON_VERSION: '3.12'       # Versi√≥n de Python utilizada
      PIP_CACHE: ~/.cache/pip      # Ruta donde se almacenar√° la cache de pip

    steps:
      # 1Ô∏è Checkout: descarga el repositorio en el runner
      - name: Checkout codigo
        uses: actions/checkout@v4
      
      # 2Ô∏è Cache: almacena dependencias pip para acelerar futuros workflows
      - name: Cache dependencia
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE }}                  # Carpeta de cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**requirements.txt') }}  # Se actualiza si cambia requirements.txt

      # 3Ô∏è Configurar Python en el runner
      - name: Instalar python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}   # Versi√≥n definida arriba

      # 4Ô∏è Instalar dependencias del proyecto
      - name: Instalar dependencias
        run: pip install -r requirements.txt

       #  Fix: agregar ruta al PYTHONPATH
      - name: Agregar carpeta del proyecto al PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

        
      # üîß Crear carpetas vac√≠as antes de subir artefactos
      - name: Crear carpetas vac√≠as
        run: mkdir -p logs reports
        

      # 5Ô∏è Ejecutar los tests automatizados
      - name: Run test
        run: python3 run_tests.py   # Corre tu script principal de pruebas

      - name: Run BDD tests         # ejecuta los test de behave
        run: python run_behave.py
        

      # 6Ô∏è Subir artefactos generados (reporte HTML, logs, screenshots, etc.)

      #  Reporte HTML de la ejecuci√≥n
      - name: Subir HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report           # Nombre del archivo visible en GitHub
          path: reports/              # Carpeta donde dej√°s tus reportes
          if-no-files-found: warn     # ‚Üê L√çNEA AGREGADA

      #  Logs completos de la suite
      - name: Subir Suite logs
        uses: actions/upload-artifact@v4 
        with:
          name: suite-log             # Nombre del artefacto
          path: logs/                 # Carpeta que contiene los logs
          if-no-files-found: warn     
